// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO1qThKTvK5nOqZoPFjxQcp5MRE54dT3Q',
    appId: '1:758657300481:web:7b2015645319e2a5806800',
    messagingSenderId: '758657300481',
    projectId: 'todolistapp-37f0c',
    authDomain: 'todolistapp-37f0c.firebaseapp.com',
    storageBucket: 'todolistapp-37f0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOoYDoypVXuIcbYXPKZkrQdjFKsfFlv9w',
    appId: '1:758657300481:android:d9a259f31478394b806800',
    messagingSenderId: '758657300481',
    projectId: 'todolistapp-37f0c',
    storageBucket: 'todolistapp-37f0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD17MQJmOB1DrTPkV0L7oUdhLrJ5VfMD-Y',
    appId: '1:758657300481:ios:a29a9fe7a862fb89806800',
    messagingSenderId: '758657300481',
    projectId: 'todolistapp-37f0c',
    storageBucket: 'todolistapp-37f0c.appspot.com',
    iosClientId: '758657300481-r9ihmvbosr7a4r64uq437osbg76na2vk.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListMakeingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD17MQJmOB1DrTPkV0L7oUdhLrJ5VfMD-Y',
    appId: '1:758657300481:ios:a29a9fe7a862fb89806800',
    messagingSenderId: '758657300481',
    projectId: 'todolistapp-37f0c',
    storageBucket: 'todolistapp-37f0c.appspot.com',
    iosClientId: '758657300481-r9ihmvbosr7a4r64uq437osbg76na2vk.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListMakeingApp',
  );
}
